4 module
js-tasks-ru/jsbasic-20230209_fkluck pull request #8
Opened 2023-03-06 17:51 UTC by fkluck

2023-03-06 17:52 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-03-07 04:09 UTC, koalex requested changes
Несмотря на то, что все тесты ОК надо исправить замечание в **4-3**

2023-03-07 04:09 UTC, koalex commented on 4-module/3-task/index.js
> +    row.setAttribute('hidden', true);
Я на занятии просил `hidden` задавать через свойство, надо исправить, вот так:
`row.hidden = true;`

2023-03-07 05:28 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-03-07 14:40 UTC, koalex approved these changes
отлично!

2023-03-07 14:40 UTC, merged